= CDI Training

This repository holds the sample application which covers the main concepts of the CDI 2.0 specification.
After working through the tasks one should be able to understand the main concepts of the CDI 2.0 specification and to use the CDI 2.0 concepts in real time applications.

The application is based on the link:https://jakarta.ee/release/8/[Jakarta-EE 8.0] link:https://jakarta.ee/specifications/cdi/2.0/[(CDI 2.0)] specification and the link:https://www.wildfly.org/[Wildfly 23.0.2.Final] application server.

Take a look at these link:presentation-v1.1.pdf[slides] for an introduction to CDI.

== Covered CDI Basics

The following CDI concepts are covered by this example

. Injection
. Scopes
. Initialization (`@PostConstruct, @PreDestroy`)
. Qualifiers
. Producer Methods/Fields
. Interceptors
. Decorators
. Events

== CDI Advanced

Additionally, to the CDI basics, this sample application provides implementations with explanations for situations we faced in our projects.

. Scopes and Concurrency +
How to provide request scoped state when using concurrency where we only can use `@Dependent, @ApplicationScoped` beans?
. Dynamic Default +
How to change the `@Default` of an CDI bean during runtime?
. Alternatives +
How and when to use `@Alternative` beans?
. Specialized +
How and when to use `@Specialized` beans, and what differs them from `@Alternative` beans?
. Registrar +
How to use a registrar to capture asynchronous executions results, which are needed by other parts of the application?
. Startup-Event +
How to notify the application about that the application has started?
. Lookup-Factory +
How to implement a factory to encapsulate the CDI programmatic bean lookup and how to manage `@Dependent` scoped beans properly?

== Used Tools

To get the application running you need the following software installed:

. link:https://jdk.java.net/java-se-ri/11[OpenJDK 11]
. link:https://www.wildfly.org/downloads/[Wildfly 23.0.2.FINAL (Jakarta EE 8 Full & Web Distribution)]
. link:https://maven.apache.org/download.cgi?Preferred=ftp://ftp.osuosl.org/pub/apache/[Maven 3.x.x]

== Accessing the application

The application can be accessed via `http://localhost:8080/cditraining/api/welcome`. +

Follow the instructions to work through the exercises.

IMPORTANT: When running in an IDE the actual port will depend on your configuration.

== Running in an IDE

Refer to the documentation of the IDE of your choice, which must provide integration for Wildfly/JBoss servers, for how to set up the project.

