= CDI Training

This repository holds the sample application which covers the main concepts of the CDI 3.0 specification.
After working through the tasks one should be able to understand the main concepts of the CDI 3.0 specification and to use the CDI 3.0 concepts in real time applications.

The application is based on the link:https://jakarta.ee/release/9/[Jakarta-EE 9] link:https://jakarta.ee/specifications/cdi/3.0/[(CDI 3.0)] specification and the link:https://www.wildfly.org/[Wildfly 26.1.0.Final] application server.

== Covered CDI Basics

The following CDI concepts are covered by this example

. Injection
. Scopes
. Initialization (`@PostConstruct, @PreDestroy`)
. Qualifiers
. Producer Methods/Fields
. Interceptors
. Decorators
. Events

== CDI Advanced

Additionally, to the CDI basics, this sample application provides implementations with explanations for situations we faced in our projects.

. Scopes and Concurrency +
How to provide request scoped state when using concurrency where we only can use `@Dependent, @ApplicationScoped` beans?
. Dynamic Default +
How to change the `@Default` of an CDI bean during runtime?
. Alternatives +
How and when to use `@Alternative` beans?
. Specialized +
How and when to use `@Specialized` beans, and what differs them from `@Alternative` beans?
. Registrar +
How to use a registrar to capture asynchronous executions results, which are needed by other parts of the application?
. Startup-Event +
How to notify the application about that the application has started?
. Lookup-Factory +
How to implement a factory to encapsulate the CDI programmatic bean lookup and how to manage `@Dependent` scoped beans properly?

== Resources

This repository provides the following pdf slides:

* link:cdi-introduction-v1.1.pdf[CDI Introduction] +
An introduction to CDI.
* link:cdi-specifications-v1.0.pdf[CDI Specs] +
A theoretical insight into the CDI specs scopes, interceptors, decorators and events.

The following resources are useful when implementing CDI backed applications:

* link:https://jakarta.ee/specifications/cdi/3.0/[CDI 3.0 Specification] +
The official CDI 3.0 specification of Jakarta EE

== Used Tools

To get the application running you need the following software installed:

. link:https://jdk.java.net/java-se-ri/17[OpenJDK 17]
. link:https://www.wildfly.org/downloads/[Wildfly 26.1.0.FINAL (Jakarta EE 9 Preview)]
. link:https://maven.apache.org/download.cgi?Preferred=ftp://ftp.osuosl.org/pub/apache/[Maven 3.6+]

== Accessing the application

The application can be accessed via `http://localhost:8080/cditraining/api/welcome`. +

Follow the instructions to work through the exercises.

IMPORTANT: When running in an IDE the actual port will depend on your configuration.

== Running in an IDE

Refer to the documentation of the IDE of your choice, which must provide integration for Wildfly/JBoss servers, for how to set up the project.

== WIKI

See the link:https://gepardec.github.io/cdi-training/[WIKI] for the development guidelines and the documentation about the components the application is based on.
